#!/bin/sh
. /sh/CFGFILE.sh
. /sh/info.sh
_wanid=$1

$IFCONFIG $interface 0.0.0.0

info_set info_wan${_wanid}_ifname $interface
info_set info_wan${_wanid}_devname $interface
info_set info_wan${_wanid}_ipaddr "0.0.0.0"
info_set info_wan${_wanid}_netmask "0.0.0.0"
info_set info_wan${_wanid}_gw "0.0.0.0"
info_set info_wan${_wanid}_domain ""
# info_set info_wan${_wanid}_dns1 "0.0.0.0"
# info_set info_wan${_wanid}_dns2 "0.0.0.0"
info_set info_wan${_wanid}_autodns1 "0.0.0.0"
info_set info_wan${_wanid}_autodns2 "0.0.0.0"

#zjx:以下信息用于页面输出
info_get info_wan${_wanid}_dns1 dns1
info_get info_wan${_wanid}_dns2 dns2
info_get info_wan${_wanid}_autodns1 autodns1
info_get info_wan${_wanid}_autodns2 autodns2
DNSCFG=/var/cfg/cfg-dns${_wanid}
echo "DNS1=$dns1" > $DNSCFG
echo "DNS2=$dns2" >> $DNSCFG
echo "AUTODNS1=$autodns1" >> $DNSCFG
echo "AUTODNS2=$autodns2" >> $DNSCFG

# zjx:以下信息用于页面输出
WANINFO=/var/wan${_wanid}.info
echo "WANIP=0.0.0.0" > $WANINFO
echo "WANMASK=0.0.0.0" >> $WANINFO
echo "WANGW=0.0.0.0" >> $WANINFO

/sh/if_down.sh $_wanid